test: main.cpp makefile
	g++ -Wall -std=c++11 main.cpp ../../common/eth/tcp_server.cpp ../../common/eth/tcp_server.h ../../common/configsection/configsection.cpp ../../common/configsection/configsection.h ../../common/log/log.cpp ../../common/log/log.h -o $@
